In [2]:
import numpy as np

## Vector and Array

In [4]:
# array()는 리스트 구조를 numpy 행렬로 만들어준다
vec = np.array([0,1,2,3,4])
length = len(vec)
print(vec)
print(length)

[0 1 2 3 4]
5


In [6]:
# Numpy 3x3 행렬 만들기
A = np.array([[0,1,2],[3,4,5],[6,7,8]])
print('A = ', A)
print(A.shape)

A =  [[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [10]:
# reshape를 통해 기존 행렬 구조를 변환
B = np.array([1,2,3,4])
C = B.reshape(2,2)
print('B = ', B)
print('C = \n', C)

B =  [1 2 3 4]
C = 
 [[1 2]
 [3 4]]


In [5]:
# arange를 통해 행렬을 자동으로 생성
B = np.arange(5)
C = np.arange(0, 10, 3) # 0~10까지 ++3하면서!
print('B : ', B)
print('C : ', C)
print(type(B))
print(type(C))

B :  [0 1 2 3 4]
C :  [0 3 6 9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
# linspace는 간격으로 정해진 개수만큼 배열 요소를 만들어준다
A = np.linspace(0,1,5)
print(A)
print(type(A))

[0.   0.25 0.5  0.75 1.  ]
<class 'numpy.ndarray'>


In [13]:
# one, zero 함수를 이용해 array를 채울 수 있다
one = np.ones((3,3))
zero = np.zeros((3,3))
print('one\n', one)
print('zero\n', zero)

one
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
zero
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# 행렬 A와 B연산 수행
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = A + B
D = A - B
print('C\n', C)
print('D\n', D)

C
 [[ 6  8]
 [10 12]]
D
 [[-4 -4]
 [-4 -4]]


In [15]:
# 행렬의 상수 곱셈 & 나눗셈
A = np.array([[1,2],[3,4]])
C = A * 10.0
D = A / 2.0
print('multiplied :\n', C)
print('divided :\n', D)

multiplied :
 [[10. 20.]
 [30. 40.]]
divided :
 [[0.5 1. ]
 [1.5 2. ]]


In [17]:
# dot product(벡터 내적)을 하기 위해 dot()를 사용함
A = np.array([1,2])
B = np.array([3,4])
dots = np.dot(A, B)
print(dots) # 3 + 8 = 11

11


In [20]:
# 2차원 내적 (그냥 행렬 곱하기넹)
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
matdot = np.dot(A, B)
print('A dot B : \n', matdot)

A dot B : 
 [[19 22]
 [43 50]]


In [21]:
# 두 개의 벡터 행렬 곱셈 (원소 위치에 맞게 곱하기)
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
matprod = A * B
print('A * B\n', matprod)

A * B
 [[ 5 12]
 [21 32]]


In [24]:
# indexing and slicing
# this is indexing
a = np.array([1,2,3,4,5,6,7,8])
print('a[0]:', a[0])
print('a[2]:', a[2])
print('a[-1]:', a[-1])

a[0]: 1
a[2]: 3
a[-1]: 8


In [26]:
# 3x3 행렬에서 원하는 요소 찾아오기
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('a[1,1] : ',a[1,1])
print('a[2,1] : ',a[2,1])
print('a[1] : ', a[1])
print('a[-1] : ', a[-1])

a[1,1] :  5
a[2,1] :  8
a[1] :  [4 5 6]
a[-1] :  [7 8 9]


In [27]:
a = np.array([99,77,88,44,33,11,22,55])
print('a[:3]', a[:3]) # 0~2번째 출력

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('a[:,0]', a[:,0]) # 세로 출력
print('a[:,2]', a[:,2])

a[:3] [99 77 88]
a[:,0] [1 4 7]
a[:,2] [3 6 9]


In [29]:
# 벡터화 기법을 이용하여 여러개의 요소에 대한 값을 한번에 얻을 수 있다.
x = np.linspace(0,2,10)
y = np.sin(x)
print(y)

[0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


In [51]:
import numpy as np
a = np.array([0,3,9,8,7,6,4,5])
print(a[3:])


[8 7 6 4 5]
