# ndarray클래스의 기본 속성

1. shape - 배열 각 차원(축)의 원소 개수(즉, 길이)를 담고 있는 튜플
2. size - 배열에 있는 전제 원소 개수
3. ndim - 차원 수(축)
4. nbytes - 데이터 저장에 사용된 바이트 수
5. dtype - 배열 원소의 데이터 유형

In [3]:
import numpy as np
data = np.array([[1,2],[3,4],[5,6]])
type(data)

numpy.ndarray

In [2]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
# 차원 수
data.ndim

2

In [4]:
# 배열 차원의 원소 개수를 담고 있는 튜플
data.shape

(3, 2)

In [5]:
# 배열에 있는 전체 원소의 개수
data.size

6

In [7]:
# 데이터 저장에 사용된 바이트 수
data.nbytes

48

## Numpy
1. int(8, 16, 32, 64) - 정수
2. uint(8, 16, 32, 64) - 부호 없는(음수가 아닌)정수
3. bool - 참/거짓
4. float(16, 32, 64, 128) - 부동소수
5. complex(64, 128, 256) - 복소수

In [9]:
np.array([1,2,3], dtype=np.int)

array([1, 2, 3])

In [10]:
np.array([1,2,3], dtype=np.float)

array([1., 2., 3.])

In [12]:
np.array([1,2,3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
data=np.array([1,2,3], dtype=np.float)
data

array([1., 2., 3.])

In [14]:
data.dtype

dtype('float64')

In [15]:
data=np.array(data, dtype=np.int)
data.dtype

dtype('int64')

In [16]:
data

array([1, 2, 3])

In [17]:
d1=np.array([1,2,3], dtype=float)
d2=np.array([1,2,3], dtype=complex)
d1+d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [19]:
(d1+d2).dtype

dtype('complex128')

In [20]:
data=np.array([1,2,3], dtype=np.complex)
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [21]:
data.real

array([1., 2., 3.])

In [23]:
data.imag # complex부분을 real number로 출력

array([0., 0., 0.])

## 배열 생성에 사용되는 Numpy 함수 요약

1. np.array 주어진 배열 원소로부터 새로운 배열을 생성. 
2. np.zeros 지정한 차원과 데이터 유형의 배열을 생성한 후 모두 0으로 채운다. 
3. np.ones 지정한 차원과 데이터 유형의 배열을 생성한 후 모두 1로 채운다. 
4. np.diag 배열의 대각에만 지정한 값을 채우고 나머지는 모두 0으로 채운다. 
5. np.arange 배열을 시작 값, 종료 값, 증가 값을 이용해 균등하게 배정된 값으로 채운다. 
6. np.linspace 배열을 시작값, 종료 값, 원소 개수에 따라 균등하게 배정된 값으로 채운다. 
7. np.logspace 배열을 시작 값, 종료 값에 따라 로그로 균등하게 배정된 값으로 채운다. 
8. np.meshgrid 1차원 좌표 벡터로부터 좌표 행렬(또는 고차원 좌표 배열)을 생성한다. 

In [40]:
data = np.array([1,2,3,4])
data

array([1, 2, 3, 4])

In [39]:
data.ndim

1

In [41]:
data = np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [42]:
data.ndim

2

In [44]:
data.shape

(2, 2)

In [45]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.ones(4)

array([1., 1., 1., 1.])

In [47]:
data=np.ones(4)
data.dtype

dtype('float64')

In [48]:
data=np.ones(4,dtype=np.int64)
data.dtype

dtype('int64')

In [49]:
x1=5.4*np.ones(10)
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [50]:
x2=np.full(10,5.4)
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [51]:
x1=np.empty(5)
x1.fill(3.0)
x1

array([3., 3., 3., 3., 3.])

In [52]:
x2=np.full(5, 3.0)
x2

array([3., 3., 3., 3., 3.])

In [53]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [58]:
# 0~10 까지 알아서 11개로 쪼개
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [59]:
np.logspace(0,2,5) #10**0=1에서 10**2=100사이의 5개 데이터 표현

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [4]:
x=np.array([-1,0,1])
y=np.array([-2,0,2])
# 1차원 좌표 벡터로부터 좌표 행렬(또는 고차원 좌표 배열)을 생성한다.
x, y=np.meshgrid(x,y)
x

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [5]:
y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [6]:
a = np.meshgrid(x,y)
a

[array([[-1,  0,  1, -1,  0,  1, -1,  0,  1],
        [-1,  0,  1, -1,  0,  1, -1,  0,  1],
        [-1,  0,  1, -1,  0,  1, -1,  0,  1],
        [-1,  0,  1, -1,  0,  1, -1,  0,  1],
        [-1,  0,  1, -1,  0,  1, -1,  0,  1],
        [-1,  0,  1, -1,  0,  1, -1,  0,  1],
        [-1,  0,  1, -1,  0,  1, -1,  0,  1],
        [-1,  0,  1, -1,  0,  1, -1,  0,  1],
        [-1,  0,  1, -1,  0,  1, -1,  0,  1]]),
 array([[-2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-2, -2, -2, -2, -2, -2, -2, -2, -2],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2]])]

In [62]:
z=(x+y)**2
z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [63]:
np.identity(4) # 1 대각행렬

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
np.eye(3, k=1) # 대각행렬의 1 위치 변경

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [65]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

## 인덱싱 및 슬라이스 표현 식
1. a[m] 인덱스가 m인 원소를 선택, 여기서 m은 정수다(0부터 시작)
2. a[-m] 리스트의 끝에서 m번째 원소를 선택. 여기서 m은 정수. 리스트의 마지막 원소는 –1, 마지막에서 두 번째 원소는 –2의 식으로 지정한다. 
3. a[m:n] 인덱스 m부터 n-1까지 원소를 선택한다(m,n은 정수).
4. a[:] 또는 a[0:-1] 지정한 축의 모든 원소를 선택
5. a[:n] 인덱스 0부터 시작해 n-1까지 원소를 선택(인덱스는 정수)
6. a[m:] 또는 a[m:-1] 인덱스 m부터 배열의 마지막 원소까지 선택(인덱스는 정수)
7. a[m:n:p] 인덱스 m부터 n(n은 제외)까지 매 p번째 원소를 선택
8. a[::-1] 모든 원소를 역순서로 선택

In [66]:
a=np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
a[0]

0

In [69]:
a[-1]

10

In [70]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [72]:
a[:5]

array([0, 1, 2, 3, 4])

In [73]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [74]:
a[::-2] # 모든 원소에서 -2번째 원소씩 선택

array([10,  8,  6,  4,  2,  0])

In [75]:
def adder(a,b):
 return a+b
adder(5,7)

12

In [76]:
(lambda a, b: a+b) (5,7)

12

In [79]:
f=lambda m, n:n+10*m
# (0~6, 0~6)을 순회하며 결과값을 전체 array로 구성
A=np.fromfunction(f, (6,6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [82]:
A[:,1] # column측을 순회하며 1번째 원소를 추출

array([ 1, 11, 21, 31, 41, 51])

In [83]:
A[1,:] # row축을 순회하며 1번째 원소를 추출

array([10, 11, 12, 13, 14, 15])

In [84]:
# (0~2, 0~2)의 원소 추출
A[:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [85]:
# (3~end, 0~3)의 원소 추출
A[3:, :3]

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [87]:
# row column을 2칸씩 뛰어 추출
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [89]:
# row를 1부터 2칸씩 띄워 추출
# col을 1부터 3칸씩 뛰어 추출
A[1::2, 1::3]

array([[11, 14],
       [31, 34],
       [51, 54]])

In [90]:
B=A[1:5, 1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [92]:
# array이기 때문에 주소값으로 B의 변화는 A에게 영향을 줌
# call by Reference
B[:,:]=0
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [93]:
# 11개원소를 0~1로 구성해
A=np.linspace(0,1,11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [94]:
A>0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [95]:
# 이 조건을 만족하는 원소만 반환해
A[A>0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [108]:
# 0~9로 구성된 array를 만들어
A=np.arange(10)
print(A)
indices=[2,4,6]
# 2, 4, 6번째를 꺼내서 B에 할당
# [[]]형식으로 call by value 가능..? 그런 것 같긴 하네
B=A[indices]
B[0]=-1
B

[0 1 2 3 4 5 6 7 8 9]


array([-1,  4,  6])

In [109]:
# 원래 A의 array가 변하지 않음 call by value (근데 왱)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
A[indices]=-1
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [111]:
A=np.arange(10)
B=A[A>5]
B[0]=-1
B

array([-1,  7,  8,  9])

In [112]:
# A>5와 같이 boolean 형식으로 해도 call by value로 작동
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
A[A>5]=-1
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

## 배열의 차원과 모양을 조작하는 numpy 함수들 요약
1. np.reshape,np.ndarray.reshape - N차원 배열 모양을 재구성한다. 원소 전체 개수는 동일해야한다. 
2. np.newaxis 배열에 새축(차원)을 추가하는데 있어 배열 인덱싱을 위해 np.newaxis를 사용한다. 
3. np.hstack 배열의 리스트를 수평(축 1을 따라)으로 쌓은다. 예를 들어 열 벡터의 리스트가 주어지면 행렬에 열을 추가한다. 
4. np.vstack 배열의 리스트를 수직(축 0을 따라)으로 쌓는다. 예를 들어 행 벡터의 리스트가 주어지면 행을 행렬에 추가한다. 

In [114]:
data=np.arange(0,5)
# 새 축(col)으로 data를 구성
column=data[:, np.newaxis]
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [115]:
# 새 축(row)로 data를 구성
row=data[np.newaxis, :]
row

array([[0, 1, 2, 3, 4]])

In [116]:
data=np.arange(5)
data

array([0, 1, 2, 3, 4])

In [117]:
# data를 수직으로 3층 쌓음
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [118]:
data=np.arange(5)
data

array([0, 1, 2, 3, 4])

In [119]:
# data를 수평으로 쌓기
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [120]:
data=data[:, np.newaxis]
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [121]:
# 세로로 구성된 array를 복사하여 수평으로 쌓음
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])